name: vanguard
channels:
  - conda-forge

dependencies:
  - python>=3.10
  - pip
  - pytorch-gpu
  - torchvision
  - cuda-version
  - numpy
  - vmtk
  - itk
  - libitk
  - imageio
  - imageio-ffmpeg

  - pip:
      - -r requirements.txt
