experiment_name: peri5_multiphase_logreg_peri_mode-3d_force_2d-False_peri_radius_mm-0
paths:
  images: /net/projects2/vanguard/MAMA-MIA-syn60868042/images
  masks: /net/projects2/vanguard/MAMA-MIA-syn60868042/segmentations/expert
  labels: /home/summe/vanguard/radiomics_baseline/labels.csv
  splits: /home/summe/vanguard/radiomics_baseline/splits_train_test_ready.csv
  outdir: /home/summe/vanguard/radiomics_baseline/outputs/peri5_multiphase_logreg_peri_mode-3d_force_2d-False_peri_radius_mm-0
  params_yaml: /home/summe/vanguard/radiomics_baseline/pyradiomics_params.yaml
  extract_outdir: /home/summe/vanguard/radiomics_baseline/outputs/shared_extraction/peri5_multiphase_logreg_peri_mode-3d_force_2d-False_peri_radius_mm-0
extract:
  image_patterns:
  - '{pid}/{pid}_0001.nii.gz'
  - '{pid}/{pid}_0002.nii.gz'
  mask_pattern: '{pid}.nii.gz'
  peri_radius_mm: 0
  peri_mode: 3d
  force_2d: false
  force_2d_dimension: 0
  n_jobs: 8
  label_override: 1
  non_scalar_handling: concat
  aggregate_stats:
  - mean
  - std
  - min
  - max
  hybrid_concat_threshold: 5
train:
  classifier: logistic
  logreg_penalty: elasticnet
  logreg_l1_ratio: 0.5
  corr_threshold: 0.9
  k_best: 50
  feature_selection: kbest
  grid_search: true
  cv_folds: 5
  include_subtype: true
