# Config file for MAMA-MIA PCR Prediction Pipeline
feature_toggles:
  use_vascular: true   # Vascular features
  use_clinical: true   # Clinical features
  use_radiomics: false # Bella's baseline (radiomics)

experiment_setup:
  name: "mamamia_baseline_v1"
  base_outdir: "./ML-Pipeline/experiments" 

model_params:
  model: "rf" 
  test_size: 0.2
  n_splits: 5 
  val_size: 0.2
  bootstrap_n: 1000
  random_state: 42

data_paths:
  feature_dir: "data/features/"
  labels_csv: "data/labels.csv"
  clinical_file: "/net/projects2/vanguard/MAMA-MIA-syn60868042/clinical_and_imaging_info.xlsx"
id_column: "case_id"
label_column: "pcr_status"