"""Summarize the final DUKE inner-wall symmetry-line QC table."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from collections.abc import Iterable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "tabular" / "duke_final_symmetry_lines.csv"
DEFAULT_OUTPUT = REPO_ROOT / "qc" / "duke_final_symmetry_lines" / "summary.md"


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _counter_table(title: str, counts: Counter[str]) -> list[str]:
    lines = [f"## {title}", "", "| value | count |", "| --- | ---: |"]
    for value, count in counts.most_common():
        label = value if value else "missing"
        lines.append(f"| `{label}` | {count} |")
    lines.append("")
    return lines


def _split_reasons(rows: Iterable[dict[str, str]]) -> Counter[str]:
    counts: Counter[str] = Counter()
    for row in rows:
        for reason in str(row.get("exclude_reason", "")).split(";"):
            if reason:
                counts[reason] += 1
    return counts


def _write_summary(
    rows: list[dict[str, str]], *, input_csv: Path, output: Path
) -> None:
    methods = Counter(row.get("side_split_method", "") for row in rows)
    confidence = Counter(row.get("tumor_side_confidence", "") for row in rows)
    include = Counter(row.get("include_for_asymmetry", "") for row in rows)
    reasons = _split_reasons(rows)
    qc_dir = output.parent
    qc_png_count = len(list(qc_dir.glob("*_side_qc_mip.png"))) if qc_dir.exists() else 0
    unexpected_methods = sorted(method for method in methods if method != "inner_walls")

    lines = [
        "# DUKE Final Symmetry-Line QC Summary",
        "",
        "Generated by `scripts/summarize_duke_final_symmetry_lines.py`.",
        "",
        f"Input CSV: `{input_csv}`",
        f"Rows: `{len(rows)}`",
        f"QC PNGs in `{qc_dir}`: `{qc_png_count}`",
        "",
        "Current method: `inner_walls`.",
        "",
        "The final Duke export is expected to contain only the breast-mask",
        "inner-wall symmetry-line method. Any non-`inner_walls` value should be",
        "treated as a QC issue before using the table downstream. Cases that",
        "cannot produce enough clean inner-wall rows should be excluded or",
        "reviewed, not assigned by a second midline-placement method.",
        "",
    ]
    if unexpected_methods:
        lines.extend(
            [
                "Unexpected method values found:",
                "",
                *[f"- `{method}`" for method in unexpected_methods],
                "",
            ]
        )
    else:
        lines.extend(["Unexpected method values found: `none`", ""])

    lines.extend(_counter_table("Split Method Counts", methods))
    lines.extend(_counter_table("Tumor-Side Confidence Counts", confidence))
    lines.extend(_counter_table("Include-For-Asymmetry Counts", include))
    if reasons:
        lines.extend(_counter_table("Exclude Reasons", reasons))
    else:
        lines.extend(["## Exclude Reasons", "", "No exclude reasons were present.", ""])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    """Write the DUKE final symmetry-line markdown summary."""
    args = _parse_args()
    rows = _read_rows(args.input)
    _write_summary(rows, input_csv=args.input, output=args.output)
    print(f"Wrote DUKE symmetry-line summary to {args.output}")


if __name__ == "__main__":
    main()
