name: Development Checks

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

jobs:
  checks:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          environment-name: vanguard
          cache-environment: true
          init-shell: bash

      - name: Lint with pre-commit
        shell: bash -l {0}
        run: pre-commit run --all-files
